- name: Update apt cache (Debian families)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Deploy index.html from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure nginx is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
